data_path: ./datasets
num_classes: 31
lr: 0.001
approach: mstn_module # source_module, dann_module, fixbi_module, mstn_module

fixbi:
  th: 2.0
  bim_start: 100
  sp_start: 100
  cr_start: 100
  lam_sd: 0.7
  lam_td: 0.3

# Optim parameters
epochs: 60
batch_size: 32
bt_size_source: common # common or number
bt_size_target: common # common or number
datasets: default # align, concat, default

gpu:
  nb_gpus: 1
  strategy:

# Logging parameters
wandb:
  project: dom_adapt
  name: run1 # use for W&B run name and for the checkpoint name

device: cpu

# Other parameters
shuffle: True
source_domain: dslr
target_domain: webcam
optimizer: sgd # sgd, adam
scheduler: cos # cos, cust
nb_wokers: 4
check: False

 
