data_path: ./datasets
num_classes: 31
lr: 0.01
approach: fixbi_module # source_module, dann_module, fixbi_module

fixbi:
  th: 2.0
  bim_start: 1
  sp_start: 7
  cr_start: 1
  lam_sd: 0.7
  lam_td: 0.3

# Optim parameters
epochs: 20
batch_size: 7

gpu:
  nb_gpus: 1
  strategy:

# Logging parameters
wandb:
  project: dom_adapt
  name: run1 # use for W&B run name and for the checkpoint name

device: cpu

# Other parameters
shuffle: True
source_domain: amazon
target_domain: dslr
nb_wokers: 4
check: False
